name: tfg
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _pytorch_select=0.2
  - _tflow_select=2.3.0
  - aiosignal=1.2.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - astor=0.8.1
  - astunparse=1.6.3
  - asynctest=0.13.0
  - attrs=21.4.0
  - backcall=0.2.0
  - beautifulsoup4=4.11.1
  - blas=1.0
  - bleach=4.1.0
  - blinker=1.4
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - c-ares=1.18.1
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - cffi=1.15.1
  - click=8.0.4
  - cloudpickle=2.0.0
  - cryptography=37.0.1
  - cudatoolkit=10.0.130
  - cudnn=7.6.5
  - cycler=0.11.0
  - cytoolz=0.11.0
  - dask-core=2021.10.0
  - dataclasses=0.8
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - expat=2.4.4
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.11.0
  - fsspec=2022.3.0
  - gast=0.4.0
  - giflib=5.2.1
  - glib=2.69.1
  - google-pasta=0.2.0
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - hdf5=1.10.6
  - icu=58.2
  - imageio=2.9.0
  - importlib-metadata=4.11.3
  - importlib_metadata=4.11.3
  - importlib_resources=5.2.0
  - intel-openmp=2022.0.1
  - ipykernel=6.9.1
  - ipython=7.31.1
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.2
  - jedi=0.18.1
  - jinja2=3.0.3
  - joblib=1.1.0
  - jpeg=9e
  - jsonschema=4.4.0
  - jupyter_client=7.3.4
  - jupyter_core=4.10.0
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=3.0.3
  - keras-preprocessing=1.1.2
  - kiwisolver=1.4.2
  - krb5=1.19.2
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libdeflate=1.8
  - libedit=3.1.20210910
  - libevent=2.1.12
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=11.2.0
  - libllvm10=10.0.1
  - libpng=1.6.37
  - libpq=12.9
  - libprotobuf=3.20.1
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtiff=4.4.0
  - libuuid=1.0.3
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.9.14
  - libxslt=1.1.35
  - locket=1.0.0
  - lz4-c=1.9.3
  - markupsafe=2.1.1
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.6
  - mistune=0.8.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - munkres=1.1.4
  - nb_conda=2.2.1
  - nb_conda_kernels=2.3.1
  - nbclient=0.5.13
  - nbconvert=6.4.4
  - nbformat=5.3.0
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - networkx=2.6.3
  - ninja=1.10.2
  - ninja-base=1.10.2
  - notebook=6.4.12
  - nspr=4.33
  - nss=3.74
  - numexpr=2.7.3
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openssl=1.1.1s
  - opt_einsum=3.3.0
  - packaging=21.3
  - pandas=1.3.5
  - pandocfilters=1.5.0
  - parso=0.8.3
  - partd=1.2.0
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=22.1.2
  - ply=3.11
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.20
  - ptyprocess=0.7.0
  - pyasn1=0.4.8
  - pycparser=2.21
  - pygments=2.11.2
  - pyjwt=2.4.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.7.13
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-flatbuffers=2.0
  - pytorch=1.3.1
  - pytorch-gpu=1.3.1
  - pytz=2022.1
  - pywavelets=1.3.0
  - pyyaml=6.0
  - pyzmq=23.2.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - readline=8.1.2
  - requests=2.28.1
  - scikit-image=0.19.2
  - scikit-learn=1.0.2
  - scipy=1.6.2
  - send2trash=1.8.0
  - setuptools=63.4.1
  - sip=6.6.2
  - six=1.16.0
  - soupsieve=2.3.1
  - sqlite=3.39.2
  - tensorboard-plugin-wit=1.8.1
  - tensorflow-base=2.4.1
  - terminado=0.13.1
  - testpath=0.6.0
  - threadpoolctl=2.2.0
  - tifffile=2020.10.1
  - tk=8.6.12
  - toml=0.10.2
  - toolz=0.11.2
  - tornado=6.1
  - traitlets=5.1.1
  - typing-extensions=4.3.0
  - typing_extensions=4.3.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.1
  - widgetsnbextension=4.0.3
  - wrapt=1.14.1
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.8.0
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - absl-py==1.2.0
    - aiohttp==3.8.3
    - async-timeout==4.0.2
    - cachetools==5.2.0
    - charset-normalizer==2.1.1
    - fire==0.4.0
    - flatbuffers==1.12
    - frozenlist==1.3.1
    - fuzzylogic==1.2.0
    - google-auth==2.11.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.47.0
    - h5py==3.7.0
    - idna==3.4
    - kaleido==0.2.1
    - keras==2.9.0
    - libclang==14.0.6
    - lightning-lite==1.8.0.post1
    - lightning-utilities==0.3.0
    - markdown==3.4.1
    - mnist==0.2.2
    - multidict==6.0.2
    - munch==2.5.0
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - oauthlib==3.2.0
    - opencv-python-headless==4.7.0.72
    - pillow==9.2.0
    - plotly==5.3.1
    - protobuf==3.19.6
    - pyasn1-modules==0.2.8
    - pytorch-lightning==1.8.0.post1
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - tenacity==8.0.1
    - tensorboard==2.9.1
    - tensorboard-data-server==0.6.1
    - tensorflow==2.9.1
    - tensorflow-estimator==2.9.0
    - tensorflow-io-gcs-filesystem==0.26.0
    - termcolor==1.1.0
    - torch==1.13.1
    - torchmetrics==0.10.2
    - torchvision==0.5.0
    - tqdm==4.64.1
    - urllib3==1.26.12
    - werkzeug==2.2.2
    - yarl==1.8.1
    - gstreamer=1.14.0
    - pytorch-gpu=1.3.1
    - ncurses=6.3
    - libxkbcommon=1.0.1
    - libedit=3.1.20210910
    - libgcc-ng=11.2.0
    - freetype=2.11.0
    - libgomp=11.2.0
    - libgfortran-ng=7.5.0
    - ld_impl_linux-64=2.38
    - intel-openmp=2022.0.1
    - libxcb=1.15
    - readline=8.1.2
    - _openmp_mutex=5.1
    - dbus=1.13.18
    - libgfortran4=7.5.0
    - gst-plugins-base=1.14.0
    - libstdcxx-ng=11.2.0
    - nss=3.74
    - tensorflow-base=2.4.1
    - nspr=4.33
    - libuuid=1.0.3
