#!/bin/bash
# Script to push python project to repository

if [ "$#" != "1" ]; then
    echo "Script requires commit message!""
    exit 0
fi

pip freeze > requirements.txt
git add .
git commit -m $1
git push
