#!/bin/bash
# Script to push python project to repository

if [ "$#" != "1" ]; then
    echo "Script requires commit message!""
    exit 0
fi

conda export tfg > conda_env.yml
git add .
git commit -m $1
git push
